### ISSUE TITLE
Struct fields don't appear until assignment

### ISSUE THREAD

**Issue by kopecs** [MarkChenYutian/C0VM-ts#9] opened 2022-10-11 21:04 UTC
**Describe the bug**

Struct fields aren't shown until they're assigned to, but should be shown immediately with the default value.

**To Reproduce**

Here's an example program to display the issue:
```
struct Y {
    int* val;
    struct Y* next;
};

struct X {
    int* p;
    char[] cs;
    struct Y* y;
};

int main() {
    struct X* a = alloc(struct X);
    a->p = alloc(int);
    *(a->p) = 15122;
    a->cs = alloc_array(char, 3);
    a->cs[0] = 'a';
    a->cs[1] = 'b';
    a->cs[2] = 'c';
    
    struct Y* b = alloc(struct Y); 
    a->y = b;
    a->y->val = a->p;
    b->next = a->y;
    return 0;
}
```
The issue can be seen at, e.g., lines 16/17.

**Expected behavior**
Structs should be shown in full at time of allocation, with default values for each field.

**Comment by MarkChenYutian** [comment] 2022-10-12 04:48
This is an expected behavior. Since the project is actually running compiled `bc0` bytecodes behind the curtain (you can see it if you open _Settings (little gear on bottom) > Advanced Settings > Expose Bytecode_

The compiled bytecode does not contain any type information so I'm doing lots of acrobatics to "reconstruct type" from bytecode and their comments.

![image](https://user-images.githubusercontent.com/47029019/195252163-5430bc57-1fc6-4678-ad64-da07f415bf0f.png)

While some information (like field name) is available by parsing through the bytecode file directly (regex match on comment), many information like type of field in struct is not available until we actually execute the `aaddf` pointer arithmetic command on some pointer. Therefore, all the fields that are not touched yet will be invisible from debug console. (We need type information to interpret the binary content in heap and display it properly on debug console!)

![image](https://user-images.githubusercontent.com/47029019/195251859-998ee010-dd06-4ca8-aaaa-f3d45a803fb4.png)

(^ This is what heap content looks like under the hood)

This is addressed a little bit, however, by "type reuse" (_Settings > Advanced Settings > Experimental - Type Reuse_). If you run the code to some intermediate breakpoint and click "Restart", the struct type information (offset, and type of field with that offset) is preserved. In this way, you can see the initial value of fields even before they are touched.

**Comment by MarkChenYutian** [comment] 2022-10-12 04:51
It is possible, however, to directly parse the C0 source code and figure out the type, offset and name of each field in struct. In fact, such tokenizer & parser for C0 already exists right now (the syntax highlighting is based on it). Maybe, MAYBE, I will try to implement something like this in the future.

**Comment by kopecs** [comment] 2022-10-12 05:00
It really sounds like just implementing a tree-walk interpreter (or something else more complex, but that would seem to me to be sufficient) instead of trying to consume bytecode is what needs to be done, at least for the memory diagram relevant featureset.

Even if this is currently the expected behaviour, I would consider this a prerequisite to using this to show examples to students.

**Comment by MarkChenYutian** [comment] 2022-10-12 05:08
Yeah... That makes sense. Or maybe I can ask iliano to dump more type information in the extended bytecode format (not exposed to students) by changing the behavior of cc0 compiler.

**Comment by kopecs** [comment] 2022-10-12 18:48
I don't think modifying the compiler is the right solution here. I can look at this a bit over break.

**Comment by MarkChenYutian** [comment] 2022-12-29 00:46
I'm trying to fix this problem by searching through the syntax tree of source code and extract the type information of structs.

**Closed** 2023-01-05 01:33 UTC
Labels: bug, VM Core
